// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptbyljgwwtoascrjexze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0Ynlsamd3d3RvYXNjcmpleHplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTIxMjYsImV4cCI6MjA2NTQ2ODEyNn0.0PegDdxn-d0rPCK8MTo-BDSawi-VI4XDtmqMie8XBAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});